# Generated by Django 5.1.7 on 2025-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
