# Generated by Django 5.1.7 on 2025-09-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_quizresult_answers_data_quizresult_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='assignment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='midterm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='quiz',
            field=models.IntegerField(default=0),
        ),
    ]
