# Generated by Django 5.1.7 on 2025-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_achievement_event_note_task_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
