# Generated by Django 5.1.7 on 2025-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_studentsemester_end_date_studentsemester_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
