# Generated by Django 5.1.7 on 2025-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
