# Generated by Django 5.1.7 on 2025-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_lecturefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturefeedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
