# Generated by Django 5.1.7 on 2025-09-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_assignment_feedback_assignment_grade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
