# Generated by Django 5.1.7 on 2025-09-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_performance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set(),
        ),
    ]
