# Generated by Django 5.1.7 on 2025-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
